theme: jekyll-theme-architect
title: Lev's homepage
description: Hi there! This is my homepage, here you will find me posting various different things, posts like pictures, walks, or stories.
plugins:
  - jekyll-seo-tag
timezone: Europe/London
encoding: utf-8
# Default front matter data so if no front matter data is set it will use the default layoout
defaults:
 -
  scope:
   path: ""
  values:
   layout: "default"
